"""Updated User Fields

Revision ID: 0e1a2e84a56a
Revises: 99834856e69f
Create Date: 2024-06-23 15:36:55.762186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1a2e84a56a'
down_revision: Union[str, None] = '99834856e69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friendship_friend_to_fkey', 'friendship', type_='foreignkey')
    op.drop_constraint('friendship_user_fkey', 'friendship', type_='foreignkey')
    op.create_foreign_key(None, 'friendship', 'users', ['friend_to'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'friendship', 'users', ['user'], ['id'], ondelete='CASCADE')
    op.drop_constraint('pending_waiting_fkey', 'pending', type_='foreignkey')
    op.drop_constraint('pending_for_confirmation_fkey', 'pending', type_='foreignkey')
    op.create_foreign_key(None, 'pending', 'users', ['waiting'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pending', 'users', ['for_confirmation'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'age')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'pending', type_='foreignkey')
    op.drop_constraint(None, 'pending', type_='foreignkey')
    op.create_foreign_key('pending_for_confirmation_fkey', 'pending', 'users', ['for_confirmation'], ['id'])
    op.create_foreign_key('pending_waiting_fkey', 'pending', 'users', ['waiting'], ['id'])
    op.drop_constraint(None, 'friendship', type_='foreignkey')
    op.drop_constraint(None, 'friendship', type_='foreignkey')
    op.create_foreign_key('friendship_user_fkey', 'friendship', 'users', ['user'], ['id'])
    op.create_foreign_key('friendship_friend_to_fkey', 'friendship', 'users', ['friend_to'], ['id'])
    # ### end Alembic commands ###
