"""Updated User Fields and Added More Sessions Fields

Revision ID: 99834856e69f
Revises: 
Create Date: 2024-06-21 19:54:08.677076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99834856e69f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('OUTDOOR_RUNNING', 'INDOOR_RUNNING', 'GYM', 'CALISTHENICS', 'OUTDOOR_TRAINING', 'SWIMMING', name='sessiontype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_verified', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('sign_up_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('friendship',
    sa.Column('friend_to', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['friend_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('friend_to', 'user')
    )
    op.create_table('pending',
    sa.Column('waiting', sa.String(), nullable=False),
    sa.Column('for_confirmation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['for_confirmation'], ['users.id'], ),
    sa.ForeignKeyConstraint(['waiting'], ['users.id'], ),
    sa.PrimaryKeyConstraint('waiting', 'for_confirmation')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_of_creation', sa.DateTime(), nullable=False),
    sa.Column('date_of_end', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('avgSpeed', sa.Float(), nullable=False),
    sa.Column('number_of_step', sa.Integer(), nullable=False),
    sa.Column('totalDistance', sa.Float(), nullable=False),
    sa.Column('session_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_type_id'], ['session_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('date_of_measurement', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('environment_data')
    op.drop_table('sessions')
    op.drop_table('pending')
    op.drop_table('friendship')
    op.drop_table('users')
    op.drop_table('session_type')
    # ### end Alembic commands ###
