"""Added Foreign key on Session

Revision ID: fc735bab3da8
Revises: 8b5a20866a96
Create Date: 2024-05-31 15:01:20.705939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc735bab3da8'
down_revision: Union[str, None] = '8b5a20866a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('session_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sessions', 'session_type', ['session_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'session_type_id')
    # ### end Alembic commands ###
